// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A cover letter generator AI agent.
 *
 * - generateCoverLetter - A function that handles the cover letter generation process.
 * - GenerateCoverLetterInput - The input type for the generateCoverLetter function.
 * - GenerateCoverLetterOutput - The return type for the generateCoverLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCoverLetterInputSchema = z.object({
  jobDescription: z.string().describe('The job description for the position.'),
  name: z.string().describe('Your full name.'),
  email: z.string().describe('Your email address.'),
  github: z.string().describe('Your github profile.'),
  linkedin: z.string().optional().describe('Your LinkedIn profile URL, if any.'),
  additionalInfo: z.string().optional().describe('Any additional information you want to include in the cover letter.'),
});
export type GenerateCoverLetterInput = z.infer<typeof GenerateCoverLetterInputSchema>;

const GenerateCoverLetterOutputSchema = z.object({
  coverLetter: z.string().describe('The generated cover letter.'),
});
export type GenerateCoverLetterOutput = z.infer<typeof GenerateCoverLetterOutputSchema>;

export async function generateCoverLetter(input: GenerateCoverLetterInput): Promise<GenerateCoverLetterOutput> {
  return generateCoverLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'coverLetterPrompt',
  input: {schema: GenerateCoverLetterInputSchema},
  output: {schema: GenerateCoverLetterOutputSchema},
  prompt: `You are an expert career advisor specializing in creating cover letters.

  You will use the job description, and applicant's information to write a cover letter.

  Applicant Name: {{{name}}}
  Applicant Email: {{{email}}}
  Applicant Github: {{{github}}}
  Applicant LinkedIn: {{{linkedin}}}
  Additional Information: {{{additionalInfo}}}

  Job Description: {{{jobDescription}}}

  Write a cover letter. Focus on the applicant's skills and experience. Be enthusiastic and professional.
  `,
});

const generateCoverLetterFlow = ai.defineFlow(
  {
    name: 'generateCoverLetterFlow',
    inputSchema: GenerateCoverLetterInputSchema,
    outputSchema: GenerateCoverLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
